In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
input_value = np.array([[0, 0], [0, 1], [1, 1], [1, 0]])

In [4]:
input_value.shape

(4, 2)

In [5]:
output = np.array([0, 0, 1, 0])

In [6]:
output = output.reshape(4, 1)

In [7]:
output.shape

(4, 1)

In [8]:
weights = np.array([[0.1], [0.3]])

In [9]:
weights

array([[0.1],
       [0.3]])

In [10]:
bias = 0.2

In [12]:
def sigmoid_func(x):
    return 1 / (1 + np.exp(-x))

In [13]:
def der(x):
    return sigmoid_func(x) * (1 - sigmoid_func(x))

In [15]:
for epochs in range(15000):
    input_arr = input_value
    weighted_sum = np.dot(input_arr, weights) + bias
    first_output = sigmoid_func(weighted_sum)
    error = first_output - output
    total_error = np.square(np.subtract(first_output, output)).mean()
    first_der = error
    second_der = der(first_output)
    derivative = first_der * second_der
    t_input = input_value.T
    final_derivative = np.dot(t_input, derivative)
    weights = weights - (0.05 * final_derivative)
    for i in derivative:
        bias = bias - (0.05 * i)

In [16]:
print(weights)
print(bias)

[[6.62916366]
 [6.62916441]]
[-10.23197316]


In [17]:
pred = np.array([1, 0])

In [18]:
result = np.dot(pred, weights) + bias

In [19]:
res = sigmoid_func(result)

In [20]:
print(res)

[0.02652435]


In [21]:
pred = np.array([1, 1])

In [22]:
result = np.dot(pred, weights) + bias

In [23]:
res = sigmoid_func(result)

In [24]:
print(res)

[0.95375065]


In [25]:
pred = np.array([0, 0])

In [26]:
result = np.dot(pred, weights) + bias

In [27]:
res = sigmoid_func(result)

In [28]:
print(res)


[3.59993686e-05]


In [29]:
pred = np.array([0, 1])

In [30]:
result = np.dot(pred, weights) + bias

In [31]:
res = sigmoid_func(result)

In [32]:
print(res)

[0.02652437]


In [33]:
import numpy as np
import pandas as pd

input_value = np.array([[0, 0], [0, 1], [1, 1], [1, 0]])
input_value.shape
# (4, 2)

output = np.array([0, 0, 1, 0])
output = output.reshape(4, 1)
output.shape
# (4, 1)

weights = np.array([[0.1], [0.3]])
weights
# array([[0.1], [0.3]])

bias = 0.2

def sigmoid_func(x):
    return 1 / (1 + np.exp(-x))

def der(x):
    return sigmoid_func(x) * (1 - sigmoid_func(x))

for epochs in range(15000):
    input_arr = input_value
    weighted_sum = np.dot(input_arr, weights) + bias
    first_output = sigmoid_func(weighted_sum)
    error = first_output - output
    total_error = np.square(np.subtract(first_output, output)).mean()
    first_der = error
    second_der = der(first_output)
    derivative = first_der * second_der
    t_input = input_value.T
    final_derivative = np.dot(t_input, derivative)
    weights = weights - (0.05 * final_derivative)
    for i in derivative:
        bias = bias - (0.05 * i)

print(weights)
# [16.57299223]
print(bias)
# [-25.14783487]

pred = np.array([1, 0])
result = np.dot(pred, weights) + bias
res = sigmoid_func(result)
print(res)
# [0.00018876]

pred = np.array([1, 1])
result = np.dot(pred, weights) + bias
res = sigmoid_func(result)
print(res)
# [0.99966403]

pred = np.array([0, 0])
result = np.dot(pred, weights) + bias
res = sigmoid_func(result)
print(res)
# [1.19793729e-11]

pred = np.array([0, 1])
result = np.dot(pred, weights) + bias
res = sigmoid_func(result)
print(res)


[[6.62916366]
 [6.62916441]]
[-10.23197316]
[0.02652435]
[0.95375065]
[3.59993686e-05]
[0.02652437]
